module.exports = {
  // Authentication Errors
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_TOKEN_EXPIRED: 'AUTH_002',
  AUTH_TOKEN_INVALID: 'AUTH_003',

  // Account Management Errors
  ACCOUNT_NOT_FOUND: 'ACC_001',
  ACCOUNT_ALREADY_EXISTS: 'ACC_002',
  ACCOUNT_BLOCKED: 'ACC_003',
  INSUFFICIENT_FUNDS: 'ACC_004',

  // Validation Errors
  VALIDATION_ERROR: 'VAL_001',
  INVALID_INPUT: 'VAL_002',

  // System Errors
  INTERNAL_SERVER_ERROR: 'SYS_001',
  DATABASE_ERROR: 'SYS_002',
  SERVICE_UNAVAILABLE: 'SYS_003'
};
